config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  has_rich_text :description

  validates :title, presence: true
  validates :list_position, numericality: { only_integer: true, greater_than: 0 }

  scope :ordered, -> { order(list_position: :asc) }

  after_commit :broadcast_list_items

  private

  def broadcast_list_items
    broadcast_replace_to(
      :funky_list_items,
      target: "list_items",
      partial: "list_items/list_items",
      locals: {
        list_items: ListItem.ordered
      }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: %i[ show edit update destroy ]

  # GET /list_items
  def index
    @list_items = ListItem.ordered
  end

  # GET /list_items/1
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  def create
    @list_item = ListItem.new(list_item_params)

    if @list_item.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to list_items_path, notice: "List item was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /list_items/1
  def update
    if @list_item.update(list_item_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to list_items_path, notice: "List item was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /list_items/1
  def destroy
    @list_item.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to list_items_url, notice: "List item was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_item_params
      params.require(:list_item).permit(:title, :description, :list_position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traillo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/list_items/_form.html.erb
<%= form_with(model: list_item, class: "contents") do |form| %>
  <% if list_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
        <% list_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :list_position %>
    <%= form.number_field :list_position, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", min: 1, step: 1 %>
  </div>

  <div class="flex gap-x-4 items-center">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Cancel", list_items_path, class: "text-gray-500 hover:text-black transition" %>
  </div>
<% end %>

app/views/list_items/_link_to_new.html.erb
<%= link_to 'New list item', new_list_item_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium text-center" %>

app/views/list_items/_list_item.html.erb
<div class="flex flex-col" data-controller="toggle">
  <div class="flex justify-between items-center">
    <div class="flex items-center text-2xl gap-x-2">
      <span class="text-gray-400 text-lg">#<%= list_item.list_position %></span>
      <span><%= list_item.title %></span>
    </div>
    <div class="flex gap-x-4">
      <div class="hidden" data-toggle-target="actionButtons">
        <div class="flex gap-x-4">
          <%= button_tag "Close", class: "hidden text-sky-700/50 hover:text-sky-700 transition", "data-toggle-target": "closeButton", "data-action": "toggle#close" %>
          <%= button_tag "Show", class: "text-emerald-600/50 hover:text-emerald-600 transition", "data-toggle-target": "showButton", "data-action": "toggle#show" %>
        </div>
      </div>

      <%= link_to "Edit", edit_list_item_path(list_item), class: "text-sky-700/50 hover:text-sky-700 transition" %>
      <%= button_to "Delete", list_item_path(list_item), class: "text-red-500/30 hover:text-red-500 transition", method: :delete, form: { "data-turbo-confirm": "Are you sure?" } %>
    </div>
  </div>

  <div data-toggle-target="toggleable">
    <p class="my-4 text-lg">
      <%= list_item.description %>
    </p>
  </div>
</div>

app/views/list_items/_list_items.html.erb
<%= turbo_frame_tag ListItem.model_name.collection, class: 'min-w-full' do %>
  <div class="my-10 flex flex-col gap-y-8">
    <% list_items.each do |list_item| %>
      <div class="flex border shadow-lg p-4 bg-gray-50 rounded-lg">
        <%= turbo_frame_tag list_item, class: "min-w-full" do %>
          <%= render list_item %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/list_items/create.turbo_stream.erb
<%=
  turbo_stream.replace(
    ListItem.model_name.collection, # => "list_items", the same identifier as used for turbo-frame in `_list_items.html.erb`
    partial: "list_items/list_items",
    locals: {
      list_items: ListItem.ordered
    }
  )
%>

<%= turbo_stream.replace ListItem.new, partial: "list_items/link_to_new" %>

app/views/list_items/destroy.turbo_stream.erb
<%=
  turbo_stream.replace(
    ListItem.model_name.collection, # => "list_items", the same identifier as used for turbo-frame in `_list_items.html.erb`
    partial: "list_items/list_items",
    locals: {
      list_items: ListItem.ordered
    }
  )
%>

app/views/list_items/edit.html.erb
<%= turbo_frame_tag @list_item do %>
  <div class="w-full">
    <h1 class="font-bold text-4xl">Editing list item</h1>
    <%= render "form", list_item: @list_item %>
  </div>
<% end %>

app/views/list_items/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">List items</h1>
  </div>

  <%= turbo_stream_from 'funky_list_items' %>
  <%= render "list_items", list_items: @list_items %>

  <%= turbo_frame_tag ListItem.new do %>
    <%= render "link_to_new" %>
  <% end %>
</div>

app/views/list_items/new.html.erb
<%= turbo_frame_tag @list_item do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New list item</h1>
    <%= render "form", list_item: @list_item %>
  </div>
<% end %>

app/views/list_items/update.turbo_stream.erb
<%=
  turbo_stream.replace(
    ListItem.model_name.collection,
    partial: "list_items/list_items",
    locals: {
      list_items: ListItem.ordered
    }
  )
%>

<%=
  turbo_stream.replace(
    @list_item,
    partial: "list_items/list_item",
    locals: {
      list_item: @list_item
    }
  )
%>